/** @format */

import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import CustomThemeProvider from "./components/CustomThemeProvider";
import Layout from "./components/Layout";
import "./globals.css";

export const metadata: Metadata = {
  title: "PLP Wine Shop",
  description: "Generated by create wine web app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='bg-Main dark:bg-Secondary-Color !important'>
        <Layout>
          <CustomThemeProvider>{children}</CustomThemeProvider>
          <Toaster
            position='bottom-right'
            toastOptions={{
              style: {
                background: "#000",
                color: "#fff",
              },
            }}
          />
        </Layout>
      </body>
    </html>
  );
}
